name: mapalus_partner
description: Platform to support local community to hopefully be able to thrive

publish_to: 'none'

version: 1.7.1+24

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  mapalus_flutter_commons:
    path: ../mapalus_flutter_commons
#    git: "https://github.com/meimodev/mapalus_flutter_commons.git"

  firebase_core: ^3.6.0
  get: ^4.6.6

  flutter_native_splash: ^2.2.16
  uuid: ^4.5.1
  camera: ^0.11.0+2
  expandable: ^5.0.1
  google_maps_flutter: ^2.9.0
  firebase_app_check: ^0.3.1+3

dev_dependencies:
  flutter_launcher_icons: ^0.14.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/icons/icon-1024x1024.png'

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100

flutter_native_splash:
  color: "#FF9800"
  image: assets/images/splash-mobile-accent-900x900.png