// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1-4-Q5kiaM-8LhVE10lSRnZb-WQp3IUo',
    appId: '1:342086903599:web:3de75bb74c2bab6dfc63da',
    messagingSenderId: '342086903599',
    projectId: 'mapalus-a26af',
    authDomain: 'mapalus-a26af.firebaseapp.com',
    storageBucket: 'mapalus-a26af.appspot.com',
    measurementId: 'G-CCTFVDBQHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChe_02W038hgDONB_56zl_PO9WI58tH6w',
    appId: '1:342086903599:android:babf5ecd424c6093fc63da',
    messagingSenderId: '342086903599',
    projectId: 'mapalus-a26af',
    storageBucket: 'mapalus-a26af.appspot.com',
  );
}
